# Generated by Django 3.1.5 on 2022-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans_list', models.ManyToManyField(blank=True, default=None, related_name='list_kino_plans', to='home.Kino')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites_list', models.ManyToManyField(blank=True, default=None, related_name='list_kino_favorites', to='home.Kino')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='list_in_plans',
            field=models.ManyToManyField(blank=True, default=None, related_name='list_user_kino_plans', to='users.Plans'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='list_of_favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='list_user_kino_favorites', to='users.Favorites'),
        ),
    ]
