# Generated by Django 3.1.5 on 2022-09-25 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0002_auto_20220920_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_in_plans', models.ManyToManyField(blank=True, default=None, related_name='list_user_kino_plans', to='home.Kino')),
                ('list_of_favorites', models.ManyToManyField(blank=True, default=None, related_name='list_user_kino_favorites', to='home.Kino')),
            ],
        ),
        migrations.RemoveField(
            model_name='plans',
            name='plans_list',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='list_in_plans',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='list_of_favorites',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
