# Generated by Django 3.1.5 on 2022-10-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0004_auto_20221024_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_favorites', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_favor_kino_favorites', to='home.kino')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='list_of_favorites',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_user_kino_favorites', to='users.favorites'),
        ),
    ]
