# Generated by Django 3.1.5 on 2022-10-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221024_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='list_of_favorites',
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_user_kino_favorites', to='users.profile'),
        ),
    ]
