# Generated by Django 3.1.5 on 2022-10-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221026_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='user_f',
        ),
    ]
