# Generated by Django 3.1.5 on 2022-11-03 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0009_auto_20221026_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='list_in_plans',
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kino', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_plan_kino_plans', to='home.kino')),
                ('user_f', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_user_kino_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
