# Generated by Django 3.1.5 on 2022-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emailsub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsub',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
