# Generated by Django 3.1.5 on 2022-11-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularkino',
            name='list_kino',
        ),
        migrations.AddField(
            model_name='popularkino',
            name='list_kino',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_kino_popular', to='home.kino'),
        ),
    ]
