# Generated by Django 3.1.5 on 2022-11-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221107_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationsKino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=144, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('list_kino', models.ManyToManyField(blank=True, related_name='list_kino_rec', to='home.Kino')),
            ],
            options={
                'verbose_name': 'Список реков кино',
                'verbose_name_plural': 'Список реков кино',
            },
        ),
        migrations.DeleteModel(
            name='NewKino',
        ),
    ]
