# Generated by Django 3.1.5 on 2022-11-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221110_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationskino',
            name='list_kino',
        ),
        migrations.AddField(
            model_name='recommendationskino',
            name='list_kino',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_kino_rec', to='home.kino'),
        ),
    ]
