# Generated by Django 4.1.3 on 2022-11-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_country_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['pk'], 'verbose_name': 'Сайдбар', 'verbose_name_plural': 'Сайдбар'},
        ),
        migrations.AlterField(
            model_name='kino',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=144, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='trailer',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Трейлер'),
        ),
    ]
